sudo: required
language: node_js
node_js:
- 8.9.4
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ce504b994273_key -iv $encrypted_ce504b994273_iv
  -in ./config/deploy_rsa.enc -out ./config/id_rsa -d
- docker build -t arablocks/test .
- docker run arablocks/test /bin/sh -c "cd /root; npm run test"
install:
- npm install --only=dev
script:
- npm run lint
cache:
  directories:
  - node_modules
