#!/bin/bash
safeRunCommand() {
  typeset cmnd="$*"
  typeset ret_code

  echo cmnd=$cmnd
  eval $cmnd

  ret_code=$?
  if [ $ret_code != 0 ]; then
    printf "Error : [%d] when executing command: '$cmndE'" $ret_code
    exit $ret_code
  fi
}

# ara node_modules/.bin to PATH
PATH=$(npm bin):$PATH

# installation
npm install -g ganache-cli truffle@4.1.14

# run local ganache node
ganache-cli -l 0x7A1200 -q &
sleep 5

command="truffle migrate --reset --network local"
safeRunCommand "$command"

# ava tests
command="ava test --verbose"
safeRunCommand "$command"

# cleanup
pkill -f ganache

rm -rf build
